service: houselist-server
frameworkVersion: 2

plugins:
    - serverless-dotenv-plugin
    - serverless-offline

provider:
    name: aws
    runtime: nodejs14.x
    lambdaHashingVersion: '20201221'

functions:
    api:
        handler: handler.handler
        events:
            - httpApi: '*'
