service: houselist-server
frameworkVersion: 2

plugins:
    - serverless-offline

provider:
    name: aws
    runtime: nodejs14.x
    lambdaHashingVersion: '20201221'

functions:
    api:
        handler: routes/index.handler
        events:
            - httpApi: '*'
