const HL_JWT_SECRET = process.env.HL_JWT_SECRET
const HL_JWT_EXPIRY = process.env.HL_JWT_EXPIRY
const HL_DB_CONNECTION_STRING = process.env.HL_DB_CONNECTION_STRING
const HL_FIREBASE_PROJECT_ID = process.env.HL_FIREBASE_PROJECT_ID
const HL_FIREBASE_CLIENT_EMAIL = process.env.HL_FIREBASE_CLIENT_EMAIL
const HL_FIREBASE_PRIVATE_KEY = process.env.HL_FIREBASE_PRIVATE_KEY
const HL_STORAGE_S3_BUCKET = process.env.HL_STORAGE_S3_BUCKET

module.exports = {
    HL_JWT_SECRET,
    HL_JWT_EXPIRY,
    HL_DB_CONNECTION_STRING,
    HL_FIREBASE_PROJECT_ID,
    HL_FIREBASE_CLIENT_EMAIL,
    HL_FIREBASE_PRIVATE_KEY,
    HL_STORAGE_S3_BUCKET,
}
